version: '3'

x-common-variables: &common-variables
  DATASOURCE_HOST: ${DB_HOST}
  DATASOURCE_USER: ${DB_USER}
  DATASOURCE_PASSWORD: ${DB_PASSWORD}
  DATASOURCE_NAME: ${DB_DATABASE}
  DATASOURCE_PORT: ${DB_PORT}
  PAYPAL_ACCOUNT: ${MY_PAYPAL_ACCOUNT}
  KAFKA_HOST: ${KAFKA_HOST}
  KAFKA_PORT: ${KAFKA_PORT}
  KAFKA_TOPIC1: ${KAFKA_TOPIC1}
  KAFKA_TOPIC2: ${KAFKA_TOPIC2}
  APP_NAME: ${APP_NAME}
  APP_PORT: ${APP_PORT}

x-xxx-common-services-config: &common-services-config
  restart: always

x-common-php-variables: &common-php-variables
  PMA_HOST: ${DB_HOST}
  PMA_PORT: ${DB_PORT}
  PMA_USER: ${DB_USER}
  PMA_PASSWORD: ${DB_ROOT_PASSWORD}
  MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  MYSQL_USER: ${DB_USER}

x-kafka-env: &kafka-env
  KAFKA_BROKER_ID: 1
  KAFKA_ADVERTISED_PORT: 9092
  BROKER_ID_COMMAND: "hostname | cut -d'-' -f2"
  KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
  KAFKA_CREATE_TOPICS: "logging:20:1,orders:20:1"
  KAFKA_LISTENERS: "PLAINTEXT://:9092"

services:
  zoo:
    <<: *common-services-config
    image: library/zookeeper:3.4.13
    environment:
      ZOO_MY_ID: 1

  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mystorage:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8082:80'
    environment:
      <<: *common-php-variables

  kafka:
    <<: *common-services-config
    environment: *kafka-env
    image: wurstmeister/kafka:2.11-2.0.0

  gestionepagamenti:
    image: gestionepagamenti
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
    depends_on:
      - kafka
      - mysqldb
    restart: always
    environment:
      <<: *common-variables

volumes:
  mystorage: