apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gestionepagamenti-db-volume
  labels:
    app: gestionepagamenti
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
